#! /usr/bin/env python
# -*- coding: utf-8 -*-

Import('RTT_ROOT')
Import('rtconfig')
from building import *
print ("sensors SConscript called\n")
#cwd     = os.path.join(str(Dir('#')), 'applications')
cwd = GetCurrentDir()

src = Glob('*.c')

#CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('app_sensors', src, depend = [''] )

Return('group')
