# for module compiling
import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]
objs = []

objs += DefineGroup('bsp', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    path = os.path.join(cwd, item)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(path, 'SConscript'))

Return('objs')
