Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('bsp', src, depend = ['BSP_USING_I2C_PCF8574'], CPPPATH = CPPPATH)

Return('group')
